//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KorsunKP_Furniture.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int IdMaster { get; set; }
        public string LastNameMaster { get; set; }
        public string FirstNameMaster { get; set; }
        public string MiddleNameMaster { get; set; }
        public System.DateTime DateOfBirthMaster { get; set; }
        public string EmailMaster { get; set; }
        public string PhoneNumberMaster { get; set; }
        public int IdStatusWorkMaster { get; set; }
        public byte[] PhotoMaster { get; set; }
    
        public virtual StatusWorkMaster StatusWorkMaster { get; set; }
        public virtual StatusWorkMaster StatusWorkMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
