//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KorsunKP_Furniture.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public Nullable<int> IdClient { get; set; }
        public int IdAddressClient { get; set; }
        public int IdFurniture { get; set; }
        public int IdOrderStatus { get; set; }
        public int IdMaster { get; set; }
        public string OrderNumber { get; set; }
        public string OrderTime { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderNote { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Client Client { get; set; }
        public virtual Furniture Furniture { get; set; }
        public virtual Master Master { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
